### ISSUE TITLE
Query about eqns 13, 18, and 20

### ISSUE THREAD

**Issue by gavinmacaulay** [ices-publications/SONAR-netCDF4#22]
@cyrilleponcelet 
Some more queries from Furuno about equations:

1. Eq. (13), Right-hand side. Shouldn't "R_z(r)" be replaced with "R_x(r)" ? ("z" with "x")
2. Eq. (18), Right-hand side, 1st term. Shouldn't "R_TCS->PCS" be replaced with "R_PCS->SCS" ?
3. Eq. (18), Right-hand side, 2nd term. Shouldn't "R_heading(ti)" be replaced with "R_z(h(ti))" for the consistency of the notation ?
4. Eq. (18), Right-hand side, 2nd term. Shouldn't "R_TCS->PCS" be placed between "R_heading" and "R_BCS->TCS" ? If yes, the definition of "R_TCS->PCS" may be better to be placed below Eq. (19).
5. Eq. (20), Left-hand side. Shouldn't "R_PCS/SCS" be replaced with "R_PCS->SCS" ? ("/" with "->")

**Comment by cyrilleponcelet** [comment]
Hi @gavinmacaulay 
I'm very glad that Furuno is having a deep look at those equations.

1. Yes
2. Yes
3. Yes
4. No, I can be wrong but I don't think. The point here is that since beams are stabilized we do not use PCS to have coordinate in SCS system. TCS is already relative to vertical, Once in TCS only a translation should be added to refer to SCS (and a rotation to take heading into account). To better understand, one can add an intermediate csr between TCS and SCS, this one being a csr with axis parallel to gravity and to sea surface but with x pointing in ship direction instead of pointing north . Change from this csr to SCS is only a rotation around Z axis taking heading into accout. When stabilized going from TCS to this csr is a pure translation of installation vector with roll and pitch applyied. Then we applyied heading rotation to go to SCS and we found our formula

5. Yes
 
see Merge #23 request for points 1,2,3,5

**Comment by akiraokunishi** [comment]
Bonjour, @cyrilleponcelet
Thank you for your answers to my questions.

4. I think that the definition of beam_stabilization may be a point. 

The NOTE above Figure 2 in Chapter 5 says "If a sonar actively alters beam pointing directions to compensate for motion of the platform, the beam_stabilisation variable is set to True, otherwise to False."

My understanding is that the "motion of the platform" includes the platform roll and pitch, but it does not include "transducer_rotation_x/y/z" that are defined as "extrinsic angular rotation about the x/y/z-axis from the transducer zero angle to the coordinate system origin zero angle" in Table 4. 

Then I think that "R_TCS->PCS" should be placed to compensate for the extrinsic angular rotations, if this understanding is reasonable.

**Comment by cyrilleponcelet** [comment]
Hi @akiraokunishi 
First of all thank you very much for spending time and having a deep look at what we wrote, it is very helpfull.

In our understanding, the transducer's installation angle transducer_rotation_x/y/z was included, that's the reason why we did not add the "R_TCS->PCS" transform. If you agree we could change the  sentence, make it more clear and replace "If a sonar actively alters beam pointing directions to compensate for motion of the platform, the..." by "If a sonar actively alters beam pointing directions to compensate for motion of the transducer including static installation angles offsets, the..."

Maybe we missed a use case, and you can react on this but the idea is that the sonar must use this installation angles and the platform attitude to compute its dynamic beam pointing angle (in order to get a target angle relatively to the SCS).

We're looking forward to hear from you on the subject or if you have any use case we didn't think of. (Please excuse us if it takes some time due to summer holiday) 

Cyrille.

**Comment by akiraokunishi** [comment]
Hello, @cyrilleponcelet

Thank you for sharing with me your thought in detail.

I think that "type of sonar" may be another point.
To my knowledge, for some sonars used for bathymetric surveys, transducer_rotation_x/y/z should be measured precisely and be compensated. On the other hand, for some sonars used for fishing operations, this compensation is not needed while the platform pitch and roll compensations are effectively used by fishermen. 

I believe it is desirable for the SONAR-netCDF4 to suit both types of sonars. 
Then I think that the definition of beam_stabilization does not need to be changed, and that your idea would be more clarified if you could replace at the beginning of Section 5.3.1 "When beam are stabilized by the sonar ..." by, for example, "When beams are stabilized and installation angles offsets are compensated by the sonar ..."

I am looking forward to hearing from you when you have time.

Akira

**Comment by cyrilleponcelet** [comment]
Hello @akiraokunishi 
Sorry for the delay to answer.

I will change Section 5.3.1 with you suggestion : "When beams are stabilized and installation angles offsets are compensated by the sonar ..."

Do you have any specific sonar in mind when you talk about sonars used for fishing operations, having pitch and roll compensated but not transducer rotation ? This could help me to fully understand where we could be missing some point.

Best regards
Cyrille.

**Comment by akiraokunishi** [comment]
Bonjour @cyrilleponcelet

Thank you for your reply and the question.

Furuno FSV-25, an omnidirectional fisheries sonar, is one of the specific sonars. 
For this sonar, typically:
1.  A sensor for measuring roll and pitch is attached to a rigid frame that supports the transducer.
2. The Compensations of "transducer_rotation_x" and "transducer_rotation_y" are not needed.
3. The Compensation of "transducer_rotation_z" is applied (ON), regardless of ON/OFF of the beam stabilisation function.
4. When the beam stabilisation function is ON, roll and pitch are measured and compensated dynamically.

I would like this information to be helpful to you.

Best regards,
Akira

**Comment by cyrilleponcelet** [comment]
Hello @akiraokunishi 
Your information are very helpfull, I'm still trying to fully understand the Furuno FSV-25 case. 
I will come back later once every thing is clear
I'm still trying to see if we need a third equation, or if this could fit in any way in the given ones. 

Cyrille

**Comment by cyrilleponcelet** [comment]
Hello @akiraokunishi 
As you mentionnend, given the measure of roll and pitch on this sonar, installation angles are taken into account by the attachement to the rigid frame.

When beam roll and pitch are compensated, I think that eq 18 as it is right now in the document is valid for Furuno case. 

Do we agree with that point ? 

I will change the §5.3.1 by  "When beams are stabilized and installation angles offsets are compensated by the sonar"

**Comment by akiraokunishi** [comment]
Hello @cyrilleponcelet

Yes, I agree with you. 
Eq. (18) is valid for the FSV-25 case when beam roll and pitch are compensated as usual.

I appreciate you for thinking deeply about our case. 

Merci,
Akira

**Comment by cyrilleponcelet** [comment]
Hi @gavinmacaulay 
I think we can close this issue
