### ISSUE TITLE
Question about date

### ISSUE THREAD

**Issue by cyrilleponcelet** [ices-publications/SONAR-netCDF4#40]
Hi, 
I'm asking myself why date are set with a unit  "nanoseconds since 1601-01-01 00:00:00Z" instead of a classical epoch time         :units = "nanoseconds since 1970-01-01 00:00:00Z"

It's pretty confusing for developpers and error prone. Is there any reason why we did not choosed POSIX Time which is the reference for most langages ?

Are we still compliant with specification if unit is set to  "nanoseconds since 1970-01-01 00:00:00Z" ?

**Comment by gavinmacaulay** [comment]
Originally, the time unit was 100 nanoseconds since 1601, but this form of time (with a value that isn't 1) is not well supported by the various tools that read CF-formatted time units, so it was changed to nanoseconds since 1601. The choice of 100 nanoseconds since 1601 was because that is the time unit used in Simrad .raw files, which comes from the time stamp used in Windows and seemed a high enough resolution for any foreseeable use.

The sonar-netcdf4 format doesn't explicitly require that time uses the unit of nanoseconds since 1601, so other forms could be used, but this adds an extra complication to software that reads the sonar-netcdf4 files (that is, work out the time format).

A possible solution is to explicitly allow a small set of time units - software that reads the files then has an easier job to work out the time format, and writing software could have a choice of units that may better suit the application? For example:

nanoseconds since 1601-01-01 00:00:00Z (the existing format)
nanoseconds since 1970-01-01 00:00:00Z (Posix time, but nanoseconds instead of seconds)
milliseconds since 1970-01-01 00:00:00Z (for less demanding time resolution and for the far future...)

These would probably all still need to be stored as a 64 bit integer...

**Comment by cyrilleponcelet** [comment]
Many thanks for the quick anwser. It will be really helpfull to me
I agree to keep 64 bit storage, thus I do not think that milliseconds precision should be proposed, let's keep nanoseconds. It's even simplier.

The choice  
* nanoseconds since 1601-01-01 00:00:00Z (the existing format)
* nanoseconds since 1970-01-01 00:00:00Z (Posix time, but nanoseconds instead of seconds)

are good to me.

I can make a pull request to add few comment in general format description about date (your 2 first paragraph seems nearly good to me as an explanation of the default choice and the fact that we could allows different units)

**Comment by gavinmacaulay** [comment]
Sounds like a good plan - we allow two (and only two) different zero times in the units.

**Comment by cyrilleponcelet** [comment]
Thanks Gavin for merging the PR
I close this issue
