### ISSUE TITLE
mean_time definition should be placed in ADCP/Mean_current

### ISSUE THREAD

**Issue by cyrilleponcelet** [ices-publications/SONAR-netCDF4#51]
Hi @SverreBerg 
I just noticed that two definition exists for the variable mean_time.
* One was added in beamGroup in commit associated with #39 
* A second definition for the variable is in Mean_current subgroup.

I think that those definition and the mean_time dimension declaration should be located in the Mean_current subgroup since that's the only place where it is used.

If you agree with this, I could make a pull request (Note that in the ADCP file I've got from 2020 , the dimension is really declared in fact in mean_current subgroup)

**Comment by SverreBerg** [comment]
Hi Cyrille,

Yes, I can agree with this.
Thanks for noticing.

Best regard,
Sverre

From: cyrilleponcelet ***@***.***>
Sent: tirsdag 14. september 2021 16:34
To: ices-publications/SONAR-netCDF4 ***@***.***>
Cc: Sverre Berg ***@***.***>; Mention ***@***.***>
Subject: [ices-publications/SONAR-netCDF4] mean_time definition should be placed in ADCP/Mean_current (#51)


This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.

Hi @SverreBerg<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSverreBerg&data=04%7C01%7Csverre.berg%40simrad.com%7C7b7726afc41f4326667308d9778cae07%7Ca113bc9e1024489c902e5ac8b5fd41ce%7C0%7C0%7C637672268356090596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PdwkSxq0cOCd2%2FGqVEFe8dZh2SG%2BLlXoefm6u8Je8iA%3D&reserved=0>
I just noticed that two definition exists for the variable mean_time.

  *   One was added in beamGroup in commit associated with #39<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fices-publications%2FSONAR-netCDF4%2Fpull%2F39&data=04%7C01%7Csverre.berg%40simrad.com%7C7b7726afc41f4326667308d9778cae07%7Ca113bc9e1024489c902e5ac8b5fd41ce%7C0%7C0%7C637672268356090596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tVHP%2FKBm73taJ2Ah215PKwxgVYMxCU6wFL09zhoDF6U%3D&reserved=0>
  *   A second definition for the variable is in Mean_current subgroup.

I think that those definition and the mean_time dimension declaration should be located in the Mean_current subgroup since that's the only place where it is used.

If you agree with this, I could make a pull request (Note that in the ADCP file I've got from 2020 , the dimension is really declared in fact in mean_current subgroup)

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fices-publications%2FSONAR-netCDF4%2Fissues%2F51&data=04%7C01%7Csverre.berg%40simrad.com%7C7b7726afc41f4326667308d9778cae07%7Ca113bc9e1024489c902e5ac8b5fd41ce%7C0%7C0%7C637672268356100558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oLEyTt9iyV8Ui4ycm26fG%2FYh5xi7bPv1UIpqHHLG%2BMw%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMLDLTHESZBSFFVQYYV4DUTUB5MMZANCNFSM5EAJX3PQ&data=04%7C01%7Csverre.berg%40simrad.com%7C7b7726afc41f4326667308d9778cae07%7Ca113bc9e1024489c902e5ac8b5fd41ce%7C0%7C0%7C637672268356100558%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DMqBhKS653eCBZmSMa%2FHUgDHzayv6x9yOcAdBN70X00%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Csverre.berg%40simrad.com%7C7b7726afc41f4326667308d9778cae07%7Ca113bc9e1024489c902e5ac8b5fd41ce%7C0%7C0%7C637672268356110506%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=grLcNQH1awoXiwIe0J17NA85hb2y%2BrTlXegOCrinmx0%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Csverre.berg%40simrad.com%7C7b7726afc41f4326667308d9778cae07%7Ca113bc9e1024489c902e5ac8b5fd41ce%7C0%7C0%7C637672268356110506%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5PH8GgpXUVovoz0t0Vabzn76jsO%2FoWihtL%2FS%2BKiwntA%3D&reserved=0>.

**Comment by cyrilleponcelet** [comment]
see #53

**Comment by cyrilleponcelet** [comment]
Can be close, see #53
