### ISSUE TITLE
Is Gain applied correctly in Type 1 conversion equation?

### ISSUE THREAD

**Issue by geoffmatt** [ices-publications/SONAR-netCDF4#75]
Not sure if this is an issue or not.
In the Type 1 Conversion Equation there is a term:
10Log10(Pt * Lambda^2 / 16 pi^2) - G

This is exactly the same Transmit Receive factor we use in Echoview to calculate Power for Simrad EK systems, except that we have "2G" instead of G. 

Now the EK systems are obviously not the same as the Simrad Omni systems, but I thought I'd check just in case this was a typo.

**Comment by gavinmacaulay** [comment]
The use of G instead of 2G was deliberate and follows the equations in: 

Macaulay, G. J., Vatnehol, S., Gammelsæter, O. B., Peña, H., and Ona, E. 2016. Practical Calibration of Ship-Mounted Omni-Directional Fisheries Sonars. Methods in Oceanography, 17: 206–220,

where I had decided that the 2 didn't need to be there, so G for Simrad omnisonars has a different meaning to the G for Simrad echosounders (in hindsight that wasn't a good decision....).

**Comment by geoffmatt** [comment]
Understood. Does that mean you'll need a different Conversion Equation for Simrad echosounders? 
Either way this issue can be closed, as there was no error :)

**Comment by gavinmacaulay** [comment]
yep, simrad echosounder equations are given in the Type 3 section.
