### ISSUE TITLE
Are equations 18 and 23 correct?

### ISSUE THREAD

**Issue by gavinmacaulay** [ices-publications/SONAR-netCDF4#8]
I have had a query from Furuno asking whether the sign of the sin terms in equations 18 and 23 are consistent with the definition of positive planes for the split-aperture angles given in Section 5.2:

"Positive minor angles occur in the positive x plane and positive major angles occur in the positive y plane."

Can you check please? @cyrilleponcelet

**Comment by cyrilleponcelet** [comment]
Hi gavin, I see two mistakes : 

- the phi and theta angle should be reversed in equation 18 and 23, phi is a rotation around x axis

- yes, my mistake we should consider a -1 * phi angle because as written "this convention does not follow the right-hand-rule for major angles".
I will make a pull request

**Comment by cyrilleponcelet** [comment]
see PR #21
